### ISSUE TITLE
optimising addition waala program

### ISSUE THREAD

**Issue by snowrlax** [pranv-sonawane/test#1]
add a good addition waala program in add.cpp

**Comment by SiaMic** [comment]
hii i would like to work on this... please add me

**Comment by SiaMic** [comment]
okay i will do this; also i dont know how to do things and i am stupid

**Comment by SiaMic** [comment]
you can close this issue now

**Comment by snowrlax** [comment]
done!

**Comment by pranv-sonawane** [comment]
bish
